### ISSUE TITLE
Transform field names within validation failed response

### ISSUE THREAD

**Issue by TUNER88** [flugger/laravel-responder#24]
Example:

#### DB fields for User:
`id`, `first_name`, `last_name`

#### API Response with transformed fields:
`GET` /api/users/1
```json
{
    "id": 1,
    "firstName: "John"
    "lastName: "Doe"
}
```

#### API Response with errors:
`POST` /api/users/

```json
{
  "status": 422,
  "success": false,
  "error": {
    "code": "validation_failed",
    "message": "The given data failed to pass validation.",
    "fields": {
      "first_name": [
        "The First Name field is required."
      ],
      "last_name": [
        "The Last Name field is required."
      ]
    }
  }
}
```

I would like to return same (transformed) field names in the error response.
What is the best way to do this?

**Comment by flugger** [comment]
Hey! The fields are taken from Laravel's validator and should reflect the fields given when you validate the data. The logic for this is all located in `Flugg\Responder\Exceptions\Http\ValidationFailedController (https://github.com/flugger/laravel-responder/blob/master/src/Exceptions/Http/ValidationFailedException.php). You may extend this to handle it the way you like, just remember to override the `failedValidation()` method to throw your exception instead of the package one. 

If you have a better suggestion on how the package could solve this, Im all ears :)

**Comment by TUNER88** [comment]
Thx for this idea and your awesome package.

I've added `failedValidation` method to my `BaseRequest` class.

```php
/**
 * Handle a failed validation attempt.
 *
 * @param  \Illuminate\Contracts\Validation\Validator $validator
 * @return void
 * @throws ApiValidationFailedException
 */
protected function failedValidation(Validator $validator)
{
    if(request()->expectsJson())
        throw new ApiValidationFailedException($validator);

    return parent::failedValidation($validator);
}
```

And I've do all attribute transformation within the `ApiValidationFailedException` class.

```php
class ApiValidationFailedException extends ValidationFailedException
{
    /**
     * Get the error data.
     *
     * @return array|null
     */
    public function getData()
    {
        $errors = $this->validator->getMessageBag()->toArray();
        return ['fields' => BaseTransformer::toCase($errors, AttributeConvention::CAMEL_CASE)];
    }
}
```

It works like a charm, I think we can close this issue.
I don't think that you can add some generic error transforming stuff to the package itself.
