### ISSUE TITLE
version 2

### ISSUE THREAD

**Issue by Hesesses** [flugger/laravel-responder#42]
Hello!

Just asking if you (@flugger) have any estimates when the new version will be available? :)

**Comment by flugger** [comment]
Hey Hese! I've had my focus on the package for the past week and getting very close to a release. I ended up rewriting a few parts of the package again as I'm only satisfied when I reach perfection :) So, unfortunately, it has taken longer to finalize version 2 than first anticipated. However, I hope it's going to be worth the wait, because it's packed with new features and the performance of the package has drastically improved (in fact, in some cases, it's even faster than using Fractal alone due to a new caching layer for the transformers). Version 2 will also introduce a complete rewrite of the documentation and a changelog so the upgrade path will be easy. 

I don't have an exact release date, but I'm keen on releasing it before July, so I can enjoy the summer. Thanks for being patient!

**Comment by Hesesses** [comment]
Awwwwwwesome!

**Comment by flugger** [comment]
Aaaaaaaaaand it's out! 🎉 Sorry for the delay - hopefully, you won't be disappointed though!
