### ISSUE TITLE
Adding pivot data on loaded relation

### ISSUE THREAD

**Issue by IlCallo** [flugger/laravel-responder#81]
Here's the scenario: there are groups and users, much like a Whatsapp group could be.
Groups and users are connected by a pivot table holding informations about when the user entered the group and whether or not he's an admin of that group.

Obviously all members of a group are accessible from a relation called "members" which is mapped to a UserTransformer using "load" property as explained in docs, is there a way to also include pivot data from the includeMembers method on a GroupTransformer?

I prefer to do the adding on the GroupTransformer rather than passing an option to the constructor of the UserTransformer which will manage members representation because other parts of the API will need to add pivot data to users about other relations in other situations and the code could become a bit messy.

Laravel 5.5 has something similar called "Conditional Pivot Information", even if it's not exactly what I'm searching for, because that feature works on the user tranformer, which I want to avoid.

It doesn't need  to be related to pivot actually, any way of adding data to every single collection member **after** it has been processed by it's transformer would be fine.

The solutions that get to my mind, even if a bit dirty, is to call transform on members relationship inside "includeMembers", then using a foreach to add pivot informations (which are stored on the Eloquent model but not on the transformed data at this point) and lastly return the newly generated array wrapping it up with the "resource()" method.

If there could be a way to say, on UserTransformer, "when you are called by a XxxTransformer, merge the array resulting by function XxxModifier (which provides in input you the original model) to the transform() result", that could be an acceptable way to solve this problem even if the code is on UserTransformer and not GroupTransformer, because code would still be enough clean and ordered.

On the other hand, moving that feature to the "related" transformer instead of the primary transformer seems to me a pain in the ass while testing, because tests about groups representation would be about UserTransformer methods instead of GroupTransformer.

I'm sorry for all the issues I'm opening, but I guess I'll stick around a little bit while I try to use this library :P

**Comment by IlCallo** [comment]
I've resolved in this way, for now

    public function includeMembers(Group $group)
    {
        $members = $group->members->map(function (User $member) {
            return array_add(transform($member), 'pivot', [
                'admin' => $member->pivot->admin,
                'created_at' => $member->pivot->created_at,
            ]);
        });
        return $this->resource($members);
    }

And the test

    public function test_include_members_should_return_members_collection_with_pivot_data()
    {
        $group = factory(Group::class)->create();
        $group->members()->attach($this->generateUser(), ['admin' => true]);
        $group->members()->attach($this->generateUser());

        $this->assertArrayStructure([
            '*' => [
                'pivot' => [
                    'admin',
                    'created_at',
                ],
            ],
        ], $this->transformer->includeMembers($group)->getData()->toArray());
    }

**Comment by Hesesses** [comment]
@IlCallo 
```
return array_add(transform($member), 'pivot', [
            'admin' => $member->pivot->admin,
            'created_at' => $member->pivot->created_at,
        ]);
```
Symfony\Component\Debug\Exception\FatalThrowableError: Type error: Too few arguments to function transform(), 1 passed in ...Transformer.php on line 43 and at least 2 expected

**Comment by Hesesses** [comment]
I'm having exactly the same problem as @IlCallo and I tried the solution above, but as i'm loading 5 different relationships, it gave error for another relation.

**Comment by IlCallo** [comment]
Can you explain better your problem?

**Comment by Hesesses** [comment]
Well the first one is how to get `return array_add(transform($member), 'pivot', [`.. transform function to use laravel-responder/src/helpers.php file instead of Illuminate/Support/helpers.php

when i replaced it with app(Transformer::class)->transform($member,null, [], []);

I'm getting error:
`Illuminate\Database\Eloquent\RelationNotFoundException: Call to undefined relationship [-another-relation-] on model [App\User].`

And -another-relation- doesnt exist on App\User, only on App\Group

**Comment by IlCallo** [comment]
I see, in Laravel 5.5 they added a transform helper, I'm on 5.4 so I had not that problem.
For the second error, check if your implicit bindings on AppServiceContainer are correct and that you imported `use Flugg\Responder\Contracts\Transformers\TransformerResolver;` and not `use Flugg\Responder\Transformers\TransformerResolver;`.
The latter gave me problems in recognizing bindings similar to yours, even if the first will fire a IDE warning because PhpDocs are not well set.

**Comment by Hesesses** [comment]
I managed to get this working with different approach:
https://laravel.com/docs/5.5/eloquent-relationships

Customizing The pivot Attribute Name
```
return $this->belongsToMany('App\Podcast')
                ->as('subscription') <- added this
                ->withTimestamps();
```

and on my UserTransformer I check if the model has the relationship:
`if ( $user->relationsToArray()['subscription'] ) // merge arrays`

**Comment by IlCallo** [comment]
The "as()" method is also a L5.5 feature :P 
I'll upgrade sooner or later :)
Anyway my concern is exactly about adding the pivot table on the UserTransformer instead of the Group one for testability and feature-logic reasons, so your solution unluckily doesn't fits my needs...
I'll wait for an answer by flugger, to see if he has some ideas

**Comment by flugger** [comment]
Hi guys. I understand the problem and handling it in the `includeMembers` or `filterMembers` method is a valid option. However, I have been wanting to copy some of the conditional attributes that Laravel introduced in 5.5 and in addition to the `whenPivotLoaded`, we could have something like `whenIncludedBy`:

```php
return [
        'id' => $user->id,
        'name' => $user->name,
        'pivot' => $this->whenIncludedBy(GroupTransformer::class, function () {
            return $user->pivot;
        }),
    ];
```

This, of course, doesn't solve your problem of moving this logic to the `GroupTransformer`, however,  letting the `UserTransformer` handle this leaves for a more lightweight solution as we don't iterate over the relations more times than necessary. May I propose making a higher-level test instead of unit testing the `GroupTransformer` methods:

```php
public function test_include_members_should_return_members_collection_with_pivot_data()
{
    $group = factory(Group::class)->create();
    $group->members()->attach($this->generateUser(), ['admin' => true]);
    $group->members()->attach($this->generateUser());

    $this->assertArrayStructure([
        '*' => [
            'members' => [
                'pivot' => [
                    'admin',
                    'created_at',
                ],
            ],
        ],
    ], transform($group, GroupTransformer::class, ['members']));
}
```

What do you think of this?

@Hesesses 
> Well the first one is how to get return array_add(transform($member), 'pivot', [.. transform function to use laravel-responder/src/helpers.php file instead of Illuminate/Support/helpers.php

I'm aware of this problem and will look into renaming the helper method. In the mean time you can resolve the service like you did or use the `Transformer` facade.

@IlCallo 
> I'm sorry for all the issues I'm opening, but I guess I'll stick around a little bit while I try to use this library :P

_Absolutely_ no problem! I highly appreciate it and hope you find what you're looking for :)

**Comment by IlCallo** [comment]
I like the `whenIncludedBy` solution, if you say that the other way around would bring performance problems.
To be consistent with all other tests I made for the project I think I'll just test those conditional fields on UserTransformer test and add a comment explaining why they are there and not in the other class, ty for the suggestion anyway :)

**Comment by IlCallo** [comment]
Maybe it can be helpful to give the including model as parameter to the `whenIncludedBy()` callback, like
    return [
        'id' => $user->id,
        'name' => $user->name,
        'pivot' => $this->whenIncludedBy(GroupTransformer::class, function (Group $group) {
            return $user->pivot;
        }),
    ];

**Comment by flugger** [comment]
I like that idea. I'll look into it when implementing the method, thanks!

**Comment by IlCallo** [comment]
As seen in #82, the method I proposed generates more problems.
If anyone has ideas about how to achieve what I need while waiting for the `whenIncludedBy` feature, I would love to hear them :D

**Comment by flugger** [comment]
I've been looking into this aswell and in order to support conditional attributes, I need to tap into each `transform` method. However, the only way I see this can be done is by renaming `transform` to something else, so Fractal calls on the package's `transform` method, which works like a proxy between Fractal and the user's transform method. I guess we could rename it to `toArray` which would be more in line with Laravel's own resource classes? This would also mean iterating through each transformed array one extra time for every resource requested. However, this is also how Laravel does it and I don't see any other way in order to support conditional attributes.

**Comment by IlCallo** [comment]
I don't know enough about the inner mechanism to propose an enhancement, my only concern is about the name.

`toArray` doesn't seem the right name for it if you wanto to stick to how Laravel use that method name.
In Laravel it's usually used as method of a model or object to give an array representation, like `toString`.
In this case we are actually transforming the data from a model taken as parameter.
I'd rather find another name, even a generic one like `process` or `mutate`, if there is no way to use  `transform`

**Comment by flugger** [comment]
Laravel 5.5 shipped with the concept of resources, where a resource class is Laravel’s answer to Fractal’s transformer classes. The laravel resources uses a said `toArray` instead of `transform`. I’ve been considering renaming transformers to resources to be more in line with Laravels new feature, however, I feel renaming `transform` to `toArray` can be a good first step in that direction.

Technically, Fractal does most of the transform working in the Scope class, which is out of my hands. This class calls the `transform` method directly, so in order to tap in to the logic, I need to extend the transform method on the abstract transformer. However, then I need to ask people to wrap their transform code in a `parent::transform` block. 

I need to iterate over the transformed data in order to apply the conditional attributes. But I might be able to solve this another way: by recursively looping over the transformed data after Fractal has processed transformers. I’m looking into that now :)

**Comment by IlCallo** [comment]
Ok, thanks for the explanation :)

**Comment by flugger** [comment]
Closing in favor of https://github.com/flugger/laravel-responder/issues/109
